name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push: # Trigger on push events
  pull_request: # Trigger on pull request events
    types: [opened, synchronize] # Trigger on PR opened and PR synchronize events
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Start webserv in background
        run: ./webserv &
      - name: Run C++ program in tests folder
        working-directory: tests # Set working directory to 'tests'
        run: |
          c++ parser.cpp -o test_parser  # Compile your C++ program
          ./test_parser simple # Run the compiled program
      - run: echo "🍏 This job's status is ${{ job.status }}."
