name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing ${{ github.repository }}
on:
  push: # Trigger on push events
  pull_request: # Trigger on pull request events
    types: [opened, synchronize] # Trigger on PR opened and PR synchronize events
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Compile webserv
        run: make re
      - name: Install Python dependencies
        run: |
          python3 -m pip install aiohttp asyncio
      - name: Start webserv in background
        run: ./webserv &
      - name: Run Config file tests
        if: always()
        working-directory: tests/config
        run: |
          ./config_test.sh
          exit_code=$?
           if [ $exit_code -ne 0 ]; then
            echo "❌ Config file tests failed. Marking run as incorrect."
            echo "::set-output name=config_tests_correct::false"
           else
            echo "✅ Config file tests passed."
            echo "::set-output name=config_tests_correct::true"
           fi
      - name: Run Python tests
        if: always()
        working-directory: tests # Set working directory to 'tests'
        run: |
          python3 general_tests.py
           exit_code=$?
           if [ $exit_code -ne 0 ]; then
            echo "❌ Tests failed. Exiting with status code $exit_code."
            exit $exit_code
           fi
      - name: Run C++ parser tests
        if: always()
        working-directory: tests # Set working directory to 'tests'
        run: |
          c++ parser.cpp -o parse && ./parse
           exit_code=$?
           if [ $exit_code -ne 0 ]; then
            echo "❌ Tests failed. Exiting with status code $exit_code."
            exit $exit_code
           fi
      - run: echo "🍏 This job's status is ${{ job.status }}."
